const target = new Date("2026-09-14T00:00:00-05:00").getTime();
let unlocked=false, attempts=0;
const teasingMessages=["Epa, epa... 😅 Todavía no puedes abrirlo. Falta un poquito.","JAJAJA ¿ya estás intentando abrirlo? 😂 Te toca esperar.","Hilly... ¿tú crees que el botón se va a desbloquear por insistencia? 👀","Bueno, bueno... ya entendí que tienes curiosidad 😭 Pero todavía falta.","🚨 DETECTADA PERSONA IMPACIENTE 🚨 El regalo sigue bajo máxima seguridad.","JAJAJA yaaa 😭 Guarda un poquito de paciencia para tu cumpleaños. 🌹","Último aviso... bueno, mentira 😂 Puedes seguir intentando, pero no se abre.","Te tengo una noticia: presionar el botón 100 veces tampoco funciona. 😌"];
function setCountdown(prefix,diff){let r=Math.max(diff,0),d=Math.floor(r/86400000);r%=86400000;let h=Math.floor(r/3600000);r%=3600000;let m=Math.floor(r/60000),s=Math.floor(r%60000/1000);document.getElementById(prefix+"days").textContent=String(d).padStart(2,"0");document.getElementById(prefix+"hours").textContent=String(h).padStart(2,"0");document.getElementById(prefix+"minutes").textContent=String(m).padStart(2,"0");document.getElementById(prefix+"seconds").textContent=String(s).padStart(2,"0");}
function updateCountdown(){const diff=target-Date.now();if(diff<=0){setCountdown("",0);unlockPage();return;}setCountdown("",diff);}
function unlockPage(){if(unlocked)return;unlocked=true;document.body.classList.remove("locked");document.getElementById("lockScreen").classList.add("hidden");document.querySelector(".hero .eyebrow").textContent="HOY · 14 DE SEPTIEMBRE · 2026";showToast("🔓 Ahora sí, Hilly. Feliz cumpleaños 🌹");burstConfetti();}
function tryOpen(){if(unlocked){openGift();return;}attempts++;const msg=teasingMessages[(attempts-1)%teasingMessages.length];document.getElementById("lockMessage").textContent=msg;showToast(msg);const b=document.getElementById("tryOpen");b.textContent=["Intentar otra vez 😅","A ver si ahora sí... 👀","Seguir intentando 😂","No me rindo 🎁","ABRIR REGALO (mentira) 😂"][Math.min(attempts-1,4)];const c=document.querySelector(".lock-card");c.classList.remove("shake");void c.offsetWidth;c.classList.add("shake");}
document.getElementById("tryOpen").addEventListener("click",tryOpen);
document.getElementById("openLetter").addEventListener("click",()=>{if(!unlocked){tryOpen();return;}document.getElementById("letterSection").scrollIntoView({behavior:"smooth"});burstConfetti();});
const gift=document.getElementById("giftBox");function openGift(){if(!unlocked){tryOpen();return;}document.getElementById("surpriseMessage").classList.add("show");burstConfetti();showToast("Sorpresa desbloqueada ❤️");}gift.addEventListener("click",openGift);gift.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openGift();}});
function showToast(text){const toast=document.getElementById("toast");toast.textContent=text;toast.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove("show"),2600);}
function burstConfetti(){const canvas=document.getElementById("confetti"),ctx=canvas.getContext("2d");canvas.width=innerWidth;canvas.height=innerHeight;const pieces=Array.from({length:110},()=>({x:innerWidth/2,y:innerHeight*.42,vx:(Math.random()-.5)*12,vy:Math.random()*-11-4,size:Math.random()*7+3,rot:Math.random()*6,vr:(Math.random()-.5)*.25,life:1}));const colors=["#ff5b83","#ffd98a","#ffffff","#ff8da9","#b991ff"];function frame(){ctx.clearRect(0,0,canvas.width,canvas.height);let alive=false;pieces.forEach((p,i)=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.28;p.rot+=p.vr;p.life-=.012;if(p.life>0){alive=true;ctx.save();ctx.globalAlpha=Math.max(p.life,0);ctx.translate(p.x,p.y);ctx.rotate(p.rot);ctx.fillStyle=colors[i%colors.length];ctx.fillRect(-p.size/2,-p.size/2,p.size,p.size*.65);ctx.restore();}});if(alive)requestAnimationFrame(frame);else ctx.clearRect(0,0,canvas.width,canvas.height);}frame();}
window.addEventListener("load",()=>setTimeout(()=>showToast("Esto es para ti, Hilly 🌹"),900));updateCountdown();setInterval(updateCountdown,1000);